### ISSUE TITLE
iWidth = 2 if select is hidden in a tab

### ISSUE THREAD

**Issue by PaulMcGuinness** [HenrikJoreteg/jquery.dd#1]
Hi there....

I've found that if the <select> is hidden in a tab, then the iWidth ends up as 2

I've added a line to mine to fix this:-

```
    // if too short - e.g. hidden on a tab somewhere.... 
    if (iWidth<10){iWidth=180;}

    iWidth = iWidth+2;     //it always give -2 width; i dont know why
```

**Comment by HenrikJoreteg** [comment]
super, super, old... closing this. Feel free to re-open or ping me if you'd like to maintain this repo.
